/*
 * sqlca.h - Simulated Oracle SQL Communication Area
 *
 * In real Pro*C, this is auto-generated by EXEC SQL INCLUDE SQLCA.
 * We provide equivalent fields for the preprocessor to use.
 */
#ifndef SIMULATED_SQLCA_H
#define SIMULATED_SQLCA_H

/* SQLCA structure — mirrors Oracle's sqlca */
typedef struct {
    char   sqlcaid[8];    /* "SQLCA  " */
    long   sqlcabc;       /* size of SQLCA = 136 */
    long   sqlcode;       /* 0 = success, < 0 = error */
    struct {
        unsigned short sqlerrml;    /* message length */
        char           sqlerrmc[256]; /* message text */
    } sqlerrm;
    char   sqlerrp[8];
    long   sqlerrd[6];    /* sqlerrd[2] = rows processed */
    char   sqlwarn[8];
    char   sqlext[8];
} SQLCA;

/* Global SQLCA instance — matches Pro*C behavior */
extern SQLCA sqlca;

/* Initialize SQLCA */
void sqlca_init(void);

/* Set error from SQLite result */
void sqlca_set_error(int sql_code, const char *msg);

/* Set success with row count */
void sqlca_set_success(int row_count);

#endif /* SIMULATED_SQLCA_H */
