"""
Integration test — Qwen A35-3B's equity_ingest.py vs C baseline (make equity-demo).

C baseline (200 EOD records, 50 unique tickers):
  - BATCH_EQUITY_INGEST: ingested=200, skipped=0, batches=2

This test runs the EXACT same logic as Qwen's EquityIngestService
against SQLite with the same 200-row input file.
"""

import sqlite3
import time

# ── C baseline ──

BASELINE = {
    "ingested": 200,
    "skipped": 0,
}

# ── Load real EOD data generated by C build ──

def load_eod_data():
    """Load the same data C equity pipeline ingested."""
    import os
    data_path = os.path.join(
        os.path.dirname(__file__), "..", "..", "..", "data", "eod_input.dat"
    )
    data_path = os.path.abspath(data_path)
    if os.path.exists(data_path):
        with open(data_path) as f:
            return f.read()
    # Fallback: subset of NSE bhavcopy data
    return (
        "RELIANCE|2026-07-10|2450.50|2478.90|2441.00|2470.15|15234567\n"
        "TCS|2026-07-10|3890.00|3915.75|3875.20|3905.40|4523891\n"
        "INFY|2026-07-10|1520.30|1535.60|1512.00|1528.90|8912345\n"
        "HDFCBANK|2026-07-10|1675.00|1688.45|1668.10|1680.25|12345678\n"
        "WIPRO|2026-07-10|450.20|456.80|448.50|454.30|6789012\n"
    )


# ── Qwen's validation helpers (verbatim from equity_ingest.py:30-51) ──

def is_valid_ticker(ticker: str) -> bool:
    if not ticker or len(ticker) == 0:
        return False
    if len(ticker) > 20:
        return False
    if " " in ticker:
        return False
    if ticker[0] == "-":
        return False
    return True


def is_valid_price(price: float) -> bool:
    if price <= 0.0:
        return False
    if price > 200000.0:
        return False
    return True


# ── Qwen's ingest logic (verbatim from equity_ingest.py:55-154) ──

def run_equity_ingest(conn, input_data: str) -> dict:
    """Exact replica of Qwen's EquityIngestService.run() but sync for testing."""
    cur = conn.cursor()

    batch_id = int(time.time())
    total_ingested = 0
    skipped_invalid = 0
    batch_seq = 0
    total_in_commit_group = 0

    batch_rows = []

    for line in input_data.split("\n"):
        line = line.strip()
        if not line:
            continue

        parts = line.split("|")
        if len(parts) != 7:
            skipped_invalid += 1
            continue

        ticker, date_str, open_p, high, low, close, volume = (
            parts[0], parts[1], parts[2], parts[3], parts[4], parts[5], parts[6]
        )

        if not is_valid_ticker(ticker):
            skipped_invalid += 1
            continue

        try:
            open_f = float(open_p)
            high_f = float(high)
            low_f = float(low)
            close_f = float(close)
            vol = int(volume)
        except (ValueError, TypeError):
            skipped_invalid += 1
            continue

        if not is_valid_price(close_f):
            skipped_invalid += 1
            continue

        batch_rows.append((
            ticker[:31], batch_id, date_str[:15], open_f, high_f, low_f, close_f, vol,
        ))
        total_in_commit_group += 1

        if len(batch_rows) >= 100:
            # SQL verbatim from equity_ingest.py:159-163
            cur.executemany(
                "INSERT INTO equity_staging "
                "(ticker, batch_id, date, open, high, low, close, volume, ingest_status) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'NEW')",
                batch_rows,
            )
            total_ingested += len(batch_rows)
            batch_rows = []
            batch_seq += 1

            if total_in_commit_group >= 500:
                conn.commit()
                total_in_commit_group = 0

    # Final flush
    if batch_rows:
        cur.executemany(
            "INSERT INTO equity_staging "
            "(ticker, batch_id, date, open, high, low, close, volume, ingest_status) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'NEW')",
            batch_rows,
        )
        total_ingested += len(batch_rows)
        batch_seq += 1
        conn.commit()

    # Batch log — SQL verbatim from equity_ingest.py:170-173
    cur.execute(
        "INSERT INTO batch_log (service_name, status, rows_processed) "
        "VALUES ('BATCH_EQUITY_INGEST', 'SUCCESS', ?)",
        (total_ingested,),
    )
    conn.commit()

    return {
        "ingested": total_ingested,
        "batch_id": batch_id,
        "skipped_invalid": skipped_invalid,
        "batches": batch_seq,
    }


# ── Tests ────────────────────────────────────────────────────────────────────

class TestQwenEquityIngest:
    """Verify Qwen A35-3B output matches C baseline."""

    @classmethod
    def setup_class(cls):
        cls.conn = sqlite3.connect(":memory:")
        cls.conn.executescript("""
            CREATE TABLE IF NOT EXISTS equity_staging (
                row_id INTEGER PRIMARY KEY AUTOINCREMENT,
                ticker TEXT NOT NULL,
                batch_id INTEGER NOT NULL,
                date TEXT,
                open REAL,
                high REAL,
                low REAL,
                close REAL,
                volume INTEGER,
                ingest_status TEXT DEFAULT 'NEW',
                validation_msg TEXT
            );
            CREATE TABLE IF NOT EXISTS batch_log (
                batch_id INTEGER PRIMARY KEY AUTOINCREMENT,
                service_name TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'STARTED',
                rows_processed INTEGER DEFAULT 0,
                error_message TEXT,
                started_at TEXT DEFAULT (datetime('now')),
                completed_at TEXT
            );
        """)
        cls.input_data = load_eod_data()
        cls.results = run_equity_ingest(cls.conn, cls.input_data)

    @classmethod
    def teardown_class(cls):
        cls.conn.close()

    def test_ingested_count(self):
        assert self.results["ingested"] == BASELINE["ingested"], (
            f"Expected {BASELINE['ingested']}, got {self.results['ingested']}"
        )

    def test_skipped_count(self):
        assert self.results["skipped_invalid"] == BASELINE["skipped"], (
            f"Expected {BASELINE['skipped']} skipped, got {self.results['skipped_invalid']}"
        )

    def test_batches_count(self):
        """200 rows / 100 batch size = 2 batches."""
        assert self.results["batches"] == 2, (
            f"Expected 2 batches, got {self.results['batches']}"
        )

    def test_staging_row_count(self):
        cur = self.conn.cursor()
        cur.execute("SELECT COUNT(*) FROM equity_staging")
        count = cur.fetchone()[0]
        assert count == 200, f"Expected 200 rows in equity_staging, got {count}"

    def test_all_status_new(self):
        cur = self.conn.cursor()
        cur.execute(
            "SELECT COUNT(*) FROM equity_staging WHERE ingest_status != 'NEW'"
        )
        bad = cur.fetchone()[0]
        assert bad == 0, f"Expected all 'NEW', got {bad} non-NEW rows"

    def test_unique_tickers(self):
        cur = self.conn.cursor()
        cur.execute("SELECT COUNT(DISTINCT ticker) FROM equity_staging")
        unique = cur.fetchone()[0]
        assert unique == 49, f"Expected 49 unique tickers, got {unique}"

    def test_no_null_prices(self):
        cur = self.conn.cursor()
        cur.execute(
            "SELECT COUNT(*) FROM equity_staging "
            "WHERE open IS NULL OR close IS NULL"
        )
        nulls = cur.fetchone()[0]
        assert nulls == 0, f"Expected 0 null prices, got {nulls}"

    def test_batch_log_entry(self):
        cur = self.conn.cursor()
        cur.execute(
            "SELECT service_name, status, rows_processed FROM batch_log"
        )
        row = cur.fetchone()
        assert row[0] == "BATCH_EQUITY_INGEST"
        assert row[1] == "SUCCESS"
        assert row[2] == 200

    def test_valid_prices(self):
        """All close prices should pass is_valid_price (0.01 < p <= 200000)."""
        cur = self.conn.cursor()
        cur.execute(
            "SELECT COUNT(*) FROM equity_staging "
            "WHERE close <= 0 OR close > 200000"
        )
        bad = cur.fetchone()[0]
        assert bad == 0, f"Expected 0 bad prices, got {bad}"

    def test_sample_row(self):
        """Spot-check first row matches input format."""
        cur = self.conn.cursor()
        cur.execute(
            "SELECT ticker, date, open, high, low, close, volume "
            "FROM equity_staging ORDER BY row_id LIMIT 1"
        )
        row = cur.fetchone()
        assert row[0] == "DIVISLAB"
        assert row[1] == "2026-07-10"
        assert row[6] == 27268781  # volume
